### ISSUE TITLE
Implement API for Returning Entity List from BabelNet

### ISSUE THREAD

**Issue by ceydanursen** [bounswe/bounswe2024group11#519] opened 2024-10-12 20:41 UTC
# 🧱 Description
The task is to design and implement a RESTful API that interfaces with the BabelNet API to return a list of entities for a given input query. The API will serve as an intermediary, allowing clients to submit a query term (such as a word or phrase) and receive a structured list of related entities, including their desciption, title, and entity id retrieved from BabelNet's multilingual semantic network.

## 📋 Acceptance Criteria

- [ ] A REST API endpoint that accepts a query string and returns a list of entities from BabelNet.
- [ ] Swagger documentation for the API is created.
- [ ] Unit tests are implemented for the endpoint.

**Comment by MucahitErdoganUnlu** [comment] 2024-10-18 16:53
Unfortunately, Babelnet API does not return description together with ids when a lemma is given. We will attempt to parse their home page HTML instead

**Comment by MucahitErdoganUnlu** [comment] 2024-10-18 19:18
there is a bug when searching the query "word". It says "'NoneType' object has no attribute 'text'"

**Comment by MucahitErdoganUnlu** [comment] 2024-10-18 19:19
and "key"

**Comment by MucahitErdoganUnlu** [comment] 2024-10-25 11:45
The problem with "word", and "key" is apparently html file that is returned after making the call has synset boxes that have no "definition". Therefore, the code gave Nontype error. The issue is fixed with checking if "definition" in a box exist or not.

**Closed by MucahitErdoganUnlu** 2024-10-25 11:45 UTC
Labels: pri: high, type: research
